//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : TestForUpload
	/// Data Source    : 172.17.23.135\MSSQLSERVER2012
	/// Server Version : 11.00.3000
	/// </summary>
	public partial class TestForUploadDB : LinqToDB.Data.DataConnection
	{
		public ITable<SysFileversion> SysFileversions { get { return this.GetTable<SysFileversion>(); } }
		public ITable<UmUserinfo> UmUserinfoes { get { return this.GetTable<UmUserinfo>(); } }

		public TestForUploadDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestForUploadDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestForUploadDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext();
		partial void InitMappingSchema();
	}

	[Table(Schema = "dbo", Name = "SYS_FILEVERSION")]
	public partial class SysFileversion
	{
		[Column(), PrimaryKey, Identity] public int ID { get; set; } // int
		[Column(), Nullable] public string VERSION { get; set; } // varchar(50)
		[Column(), Nullable] public string FILENAME { get; set; } // varchar(200)
		[Column(), Nullable] public string MD5 { get; set; } // varchar(1024)
		[Column(), Nullable] public byte[] IMG { get; set; } // image
		[Column("PROGRAM_NAME"), Nullable] public string ProgramName { get; set; } // varchar(50)
		[Column("UPLOAD_TIME"), Nullable] public DateTime? UploadTime { get; set; } // datetime
	}

	[Table(Schema = "dbo", Name = "UM_USERINFO")]
	public partial class UmUserinfo
	{
		[Column(), Identity] public decimal ID { get; set; } // decimal(18, 0)
		[Column("USER_NAME"), Nullable] public string UserName { get; set; } // varchar(50)
		[Column("LOGIN_NAME"), PrimaryKey, NotNull] public string LoginName { get; set; } // varchar(50)
		[Column("DPT_CODE"), Nullable] public string DptCode { get; set; } // varchar(50)
		[Column(), Nullable] public string PASSWORD { get; set; } // varchar(50)
		[Column("CREATE_TIME"), Nullable] public DateTime? CreateTime { get; set; } // datetime
		[Column(), Nullable] public string CREATOR { get; set; } // varchar(50)
		[Column("IS_STOP"), Nullable] public int? IsStop { get; set; } // int
		[Column(), Nullable] public string TEL { get; set; } // varchar(50)
		[Column(), Nullable] public string SEX { get; set; } // varchar(50)
		[Column(), Nullable] public string REMARK { get; set; } // varchar(50)
		[Column(), Nullable] public int? DELT { get; set; } // int
		[Column("LOGIN_2KEN"), Nullable] public string Login2ken { get; set; } // varchar(50)
		[Column("EMPLOYEE_NUM"), Nullable] public string EmployeeNum { get; set; } // varchar(50)
		[Column("LAST_TIME"), Nullable] public DateTime? LastTime { get; set; } // datetime
		[Column("EXT_GUID_1"), Nullable] public string ExtGuid1 { get; set; } // varchar(50)
		[Column("COMP_CODE"), Nullable] public string CompCode { get; set; } // varchar(50)
	}

	public static partial class TableExtensions
	{
		public static SysFileversion Find(this ITable<SysFileversion> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static UmUserinfo Find(this ITable<UmUserinfo> table, string LoginName)
		{
			return table.FirstOrDefault(t =>
				t.LoginName == LoginName);
		}
	}
}

#pragma warning restore 1591
